# GitLab CI Pipeline
# https://docs.gitlab.com/ee/ci/yaml/

workflow:
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

stages:
- devcontainer
- pages

devcontainer:
  stage: devcontainer
  rules:
  - changes:
    - ".devcontainer/devcontainer.json"
    - ".devcontainer/*/devcontainer-feature.json"
    - ".devcontainer/*/install.sh"
    - ".devcontainer/init.sh"
    - "$CI_CONFIG_PATH"
  image: docker:latest
  services:
  - docker:dind
  variables:
    DOCKER_TLS_CERTDIR: /certs
  before_script:
  - apk add --no-cache g++ make nodejs npm python3
  - npm install -g @devcontainers/cli
  - echo "CI_REGISTRY_USER='$CI_REGISTRY_USER'"
  - echo "CI_REGISTRY_IMAGE='$CI_REGISTRY_IMAGE'"
  - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
  - >
    devcontainer build --log-level debug
    --workspace-folder . --push
    --image-name "$CI_REGISTRY_IMAGE"
    --cache-from "$CI_REGISTRY_IMAGE"

pages:
  stage: pages
  rules:
  - changes:
    - "assets/**/*"
    - "config/*/*"
    - "content/**/*"
    - "data/**/*"
    - "layouts/**/*"
    - "static/**/*"
    - "hugo.yml"
    - "$CI_CONFIG_PATH"
  image: "$CI_REGISTRY_IMAGE"
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    HUGO_ENVIRONMENT: production
    HUGO_BASEURL: $CI_PAGES_URL
  script:
  - .devcontainer/init.sh
  - .devcontainer/build.sh
  artifacts:
    paths:
    - public
