# GitLab CI Pipeline
# https://docs.gitlab.com/ee/ci/yaml/

workflow:
  rules:
  - if: $CI_COMMIT_REF_NAME == $CI_DEFAULT_BRANCH

stages:
# - devcontainer
- pages

# FIXME: cannot create and push Docker image due to a bug in devcontainer CLI
# devcontainer:
#   stage: devcontainer
#   rules:
#   - changes:
#     - ".devcontainer/devcontainer.json"
#     - ".devcontainer/*/devcontainer-feature.json"
#     - ".devcontainer/*/install.sh"
#     - ".devcontainer/init.sh"
#     - "$CI_CONFIG_PATH"
#   image: docker:latest
#   services:
#   - docker:dind
#   variables:
#     DOCKER_TLS_CERTDIR: /certs
#   before_script:
#   - apk add --no-cache g++ make nodejs npm python3
#   - npm install -g @devcontainers/cli
#   - echo "$CI_REGISTRY_PASSWORD" | docker login --username "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
#   script:
#   - >
#     devcontainer build
#     --workspace-folder . --push
#     --image-name "$CI_REGISTRY_IMAGE"
#     --cache-from "$CI_REGISTRY_IMAGE"

pages:
  stage: pages
  rules:
  - changes:
    - "assets/**/*"
    - "config/*/*"
    - "content/**/*"
    - "data/**/*"
    - "layouts/**/*"
    - "static/**/*"
    - "hugo.yml"
    - "$CI_CONFIG_PATH"
  # image: "$CI_REGISTRY_IMAGE"
  image: "ghcr.io/invasy/invasy.github.io:latest"  # FIXME: replace with GitLab registry image
  variables:
    GIT_SUBMODULE_STRATEGY: recursive
    HUGO_ENVIRONMENT: production
    HUGO_BASEURL: $CI_PAGES_URL
  script:
  - .devcontainer/init.sh
  - .devcontainer/build.sh
  artifacts:
    paths:
    - public
