# Gitpod configuration
# https://www.gitpod.io/docs/references/gitpod-yml

image:
  file: .devcontainer/Dockerfile
tasks:
- init: .devcontainer/init.sh
ports:
- name: Hugo Server
  port: 1313
  visibility: private
  onOpen: open-browser
vscode:
  extensions:
  - 'asciidoctor.asciidoctor-vscode'
  - 'bierner.github-markdown-preview'
  - 'bierner.markdown-checkbox'
  - 'bierner.markdown-emoji'
  - 'bierner.markdown-footnotes'
  - 'bierner.markdown-mermaid'
  - 'bierner.markdown-preview-github-styles'
  - 'bierner.markdown-yaml-preamble'
  - 'budparr.language-hugo-vscode'
  - 'codezombiech.gitignore'
  - 'DavidAnson.vscode-markdownlint'
  - 'ecmel.vscode-html-css'
  - 'EditorConfig.EditorConfig'
  - 'esbenp.prettier-vscode'
  - 'GitHub.remotehub'
  - 'GitHub.vscode-github-actions'
  - 'GitHub.vscode-pull-request-github'
  - 'GitLab.gitlab-workflow'
  - 'golang.go'
  - 'James-Yu.latex-workshop'
  - 'lextudio.restructuredtext'
  - 'mads-hartmann.bash-ide-vscode'
  - 'ms-azuretools.vscode-docker'
  - 'ms-python.python'
  - 'ms-python.vscode-pylance'
  - 'ms-vscode.makefile-tools'
  - 'ms-vscode.vscode-typescript-next'
  - 'redhat.vscode-xml'
  - 'redhat.vscode-yaml'
  - 'timonwong.shellcheck'
  - 'unifiedjs.vscode-remark'
  - 'vscode-icons-team.vscode-icons'
  - 'yzhang.markdown-all-in-one'
github:
  prebuilds:
    master: true
    branches: false
    pullRequests: false
    pullRequestsFromForks: false
    addComment: true
    addBadge: true
    addLabel: prebuilt-in-gitpod
