default: true
MD013:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  code_blocks: true
  tables: false
  headings: true
  headers: true
  strict: false
  stern: false
MD022:
  lines_above: 0
  lines_below: 0
MD024: false
MD025: false
MD031: false
MD032: false
MD040: false