default: true
ul-indent:
  indent: 4
line-length:
  line_length: 120
  heading_line_length: 80
  code_block_line_length: 120
  tables: false
no-duplicate-heading: false
single-h1: false
fenced-code-language: false
first-line-h1: false