# Bitbucket Pipeline
#
# Documntation:
# - https://support.atlassian.com/bitbucket-cloud/docs/bitbucket-pipelines-configuration-reference/
# - https://support.atlassian.com/bitbucket-cloud/docs/variables-and-secrets/

image:
  name: ghcr.io/invasy/invasy.github.io:latest
  username: invasy
  password: $GITHUB_TOKEN

pipelines:
  branches:
    master:
    - step:
        name: Build and publish
        deployment: production
        script:
        - ./bitbucket-pages.sh
