# Bitbucket Pipeline
# https://support.atlassian.com/bitbucket-cloud/docs/bitbucket-pipelines-configuration-reference/

image:
  name: ghcr.io/invasy/invasy.github.io:latest
  username: invasy
  password: $GITHUB_TOKEN

pipelines:
  branches:
    master:
    - step:
        name: Build and publish
        deployment: production
        script:
        - ./bitbucket-pages.sh
