# Bitbucket Pipeline
# https://support.atlassian.com/bitbucket-cloud/docs/bitbucket-pipelines-configuration-reference/

image:
  name: ghcr.io/invasy.github.io
  username: $GITHUB_USERNAME
  password: $GITHUB_TOKEN

pipelines:
  branches:
    master:
    - step:
        name: Build and publish
        deployment: production
        script:
        - bitbucket-pages.sh
