# GitHub Actions Workflow
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Build dev container image

on:
  push:
    paths:
    - ".devcontainer/devcontainer.json"
    - ".devcontainer/*/devcontainer-feature.json"
    - ".devcontainer/*/install.sh"
    - ".devcontainer/init.sh"
    - ".github/workflows/devcontainer.yml"
    branches-ignore:
    - "dependabot/**"
  workflow_dispatch:

permissions:
  id-token: write
  packages: write
  pages: write

concurrency:
  group: devcontainer
  cancel-in-progress: true

jobs:
  prebuild:
    name: Build dev container image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Build dev container image
      uses: devcontainers/ci@v0.3
      with:
        imageName: ghcr.io/${{ github.repository }}
        cacheFrom: ghcr.io/${{ github.repository }}
        push: filter
        refFilterForPush: ${{ format('refs/heads/{0}', github.event.repository.default_branch) }}
