# GitHub Actions Workflow
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Build and deploy pages

on:
  push:
    paths:
    - "assets/**/*"
    - "config/*/*"
    - "content/**/*"
    - "data/**/*"
    - "layouts/**/*"
    - "static/**/*"
    - "hugo.yml"
    - ".github/workflows/pages.yml"
    branches-ignore:
    - "dependabot/**"
  workflow_dispatch:

permissions:
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    name: Build pages
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/${{ github.repository }}:latest
    env:
      HUGO_ENVIRONMENT: production
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive
    - name: Initialize environment
      run: .devcontainer/init.sh
    - name: Build
      run: .devcontainer/build.sh
    - name: Upload pages
      uses: actions/upload-pages-artifact@v4
      with:
        path: ./public

  deploy:
    name: Deploy pages
    if: github.ref_name == github.event.repository.default_branch
    needs:
    - build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v1
      id: deployment
