# GitHub Actions Workflow
# https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Build and deploy

on:
  push:
    branches-ignore:
    - 'dependabot/**'
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  pages: write

concurrency:
  group: pages
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Setup Go
      uses: actions/setup-go@v3
      with:
        go-version: stable

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: latest
        extended: true

    - name: Setup Pagefind
      uses: jaxxstorm/action-install-gh-release@v1.10.0
      with:
        repo: CloudCannon/pagefind

    - name: Checkout
      uses: actions/checkout@v3
      with:
        submodules: recursive

    - name: Update Hugo modules
      run: hugo mod get -u

    - name: Build
      run: >-
        hugo
        --environment=production
        --cleanDestinationDir
        --minify
        --printI18nWarnings
        --printPathWarnings
        --printUnusedTemplates
        --templateMetrics
        --templateMetricsHints
        --logFile=hugo.log

    - name: Upload Hugo log
      uses: actions/upload-artifact@v3
      with:
        name: hugo-log
        path: hugo.log

    - name: Make Pagefind index
      run: pagefind --source public

    - name: Upload pages
      uses: actions/upload-pages-artifact@v1
      with:
        path: ./public

  deploy:
    if: github.ref_name == github.event.repository.default_branch
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
    - name: Deploy
      uses: actions/deploy-pages@v1
      id: deployment
